### ISSUE TITLE
Week1-Assignment-3

### ISSUE THREAD

**Issue by azole** [JohnPantsWork/remote-assignments#1]
做得很好喔，這邊問一個進階問題，如果 `toNumber` 的輸入不只是 a, b, c, d, e 五種字母，可能會有 a ~ z 26 個字母，這樣有沒有更合適的做法呢？

**Comment by JohnPantsWork** [comment]
哈囉老師~我改用Ascii編碼去計算，假設依舊以大寫字母A與小寫字母a當作數字1，程式碼依照字母轉換後Ascii編碼的十進位再分別減去64跟96，可得到對應26個字母的數字，雖然有解決，但神秘數字加在程式碼中好像不太好XD
Ascii版本先更新上去了～https://johnpantswork.github.io/remote-assignments/Week-1/Assignment-3/index.html

**Comment by azole** [comment]
對，是不太好，那 A/a/Z/z 的 ascii 怎麼來的？能不能再透過什麼程式取得，而不是寫死呢？

**Comment by JohnPantsWork** [comment]
老師～這邊改了一個做法
1. 首先判斷唯一的規則是a=1，於是我設定一個常數為1，代表外部來的規則。
2. 接著設定第二個常數，該常數是透過大寫Ａ字母的ASCII編碼減去外部規則，會得到一個固定的差。
3. 在toNumber裡面，將所有input先轉換成大寫，然後減去第二個常數，便完成轉換數字，不確定這樣有沒有稍微優化到><，大致程式碼如下：

const a_to_num = 1; //outer rule
const asciiToNumGap = 'A'.charCodeAt(0)-a_to_num;

function toNumber(input){
    let arr=[];
    input.forEach(element => {
        let upperCase=element.toUpperCase();
        let asciiCode = upperCase.charCodeAt(0);
        arr.push(asciiCode-asciiToNumGap);
    });
    return arr;
}

**Comment by azole** [comment]
為什麼會需要轉換成大寫呢？

其實我覺得你上一個版本就很不錯，不過你自己有注意到在程式碼中神秘數字不好，所以我倒覺得在上一個版本中，只需要把神秘數字改成用最新版本的 `'A'.charCodeAt(0)` 取得，這樣就優化成沒有神秘數字了，對吧？

**Comment by JohnPantsWork** [comment]
對耶！
現在我把所有神奇數字改成ascii編碼顯示了，確實是沒有神秘數字了，也可以運行。

function toNumber(input){
    let arr=[];
    input.forEach(element => {
        let asciiElm = element.charCodeAt(0);
        if(asciiElm>='A'.charCodeAt(0) && asciiElm<='Z'.charCodeAt(0)){
            arr.push(asciiElm-'A'.charCodeAt(0));
        }else if (asciiElm>='a'.charCodeAt(0) && asciiElm<='z'.charCodeAt(0)){
            arr.push(asciiElm-'a'.charCodeAt(0));
        }
        else{
            arr.push(element);
            console.log(`The element ${element} is not a letter`);
        }
    });
    return arr;
}

**Comment by azole** [comment]
可以關掉這個 issue 了。
